# Generated by Django 6.0.5 on 2026-05-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('nip', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(max_length=150)),
                ('lieu_residence', models.CharField(max_length=150)),
                ('qualite', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('arrondissement', models.CharField(blank=True, max_length=100)),
                ('centre_vote', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('date_adhesion', models.DateField()),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adhérent',
                'verbose_name_plural': 'Adhérents',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
